/**
 * Self-host the UI fonts (Fraunces variable + IBM Plex Mono, both SIL OFL).
 *
 *   node scripts/dev/fetch-fonts.mjs
 *
 * Downloads latin + latin-ext woff2 subsets from Google Fonts into
 * public/fonts/ and writes app/fonts/fonts.css with @font-face rules
 * (unicode-range preserved). Run only when changing the font set — the
 * generated files are committed so builds never need network access.
 */
import fs from "node:fs";
import path from "node:path";

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const FAMILIES = [
  {
    css: "https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,100..900;1,9..144,100..900&display=swap",
    name: "Fraunces",
  },
  {
    css: "https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&display=swap",
    name: "IBM Plex Mono",
  },
];
const SUBSETS = new Set(["latin", "latin-ext"]);

const outDir = path.join(process.cwd(), "public", "fonts");
const cssOut = path.join(process.cwd(), "app", "fonts", "fonts.css");
fs.mkdirSync(outDir, { recursive: true });
fs.mkdirSync(path.dirname(cssOut), { recursive: true });

let css = `/* GENERATED by scripts/dev/fetch-fonts.mjs — do not edit by hand.
   Fraunces (c) The Fraunces Project Authors, IBM Plex Mono (c) IBM Corp.
   Both licensed under the SIL Open Font License 1.1 — self-hosting permitted. */\n`;

let fileCount = 0;
for (const fam of FAMILIES) {
  const res = await fetch(fam.css, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`css fetch failed: ${res.status}`);
  const text = await res.text();
  // blocks look like: /* latin-ext */\n@font-face { ... url(https://...woff2) ... }
  const blockRe = /\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[\s\S]*?\})/g;
  let m;
  while ((m = blockRe.exec(text)) !== null) {
    const subset = m[1];
    if (!SUBSETS.has(subset)) continue;
    let block = m[2];
    const urlM = block.match(/url\((https:[^)]+\.woff2)\)/);
    if (!urlM) continue;
    const styleM = block.match(/font-style:\s*(\w+)/);
    const weightM = block.match(/font-weight:\s*([\d\s]+)/);
    const slugName = `${fam.name.toLowerCase().replace(/\s+/g, "-")}-${(styleM?.[1] ?? "normal")}-${(weightM?.[1] ?? "400").trim().replace(/\s+/g, "-")}-${subset}.woff2`;
    const fileRes = await fetch(urlM[1], { headers: { "User-Agent": UA } });
    if (!fileRes.ok) throw new Error(`font fetch failed: ${urlM[1]}`);
    fs.writeFileSync(path.join(outDir, slugName), Buffer.from(await fileRes.arrayBuffer()));
    fileCount++;
    block = block.replace(urlM[1], `/fonts/${slugName}`);
    css += `/* ${fam.name} ${subset} */\n${block}\n`;
  }
}

fs.writeFileSync(cssOut, css, "utf8");
console.log(`fetched ${fileCount} woff2 files -> public/fonts, css -> app/fonts/fonts.css`);
